---

- name: Download alertmanager
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/alertmanager-{{ version }}.linux-amd64.tar.gz

- name: Unarchive alertmanager
  unarchive:
    src: /tmp/alertmanager-{{ version }}.linux-amd64.tar.gz
    dest: "{{ install_dir }}"
    remote_src: yes

- name: Create systemd service unit
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - reload systemd

- name: Ensure alertmanager started and enabled
  systemd:
    name: alertmanager
    state: started
    enabled: yes
  