---

- name: Download node exporter
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/node_exporter-{{ version }}.linux-amd64.tar.gz

- name: Extract node exporter
  unarchive:
    src: /tmp/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: "{{ install_dir }}"
    remote_src: yes

- name: Create systemd service unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - reload systemd

- name: Ensure node_exporter is started and enabled
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - node_exporter