---

- name: Download prometheus
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/prometheus-{{ version }}.linux-amd64.tar.gz

- name: Extract prometheus
  unarchive:
    src: /tmp/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Create systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - reload systemd

- name: Create prometheus config
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus-{{ version }}.linux-amd64/prometheus.yml
  notify:
    - restart prometheus

- name: Ensure prometheus started and enabled
  systemd:
    name: prometheus
    state: started
    enabled: yes